# Cloud Build configuration for AMR K. pneumoniae pipeline
# Builds container and optionally deploys to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: 
      - 'build'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID}'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'
    waitFor: ['-']

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'
    waitFor: ['build-image']

  # Step 3: Test the container (optional)
  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID}'
    id: 'test-container'
    entrypoint: 'snakemake'
    args: ['--version']
    waitFor: ['push-image']

  # Step 4: Deploy to Cloud Run (conditional)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloudrun'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_CLOUDRUN}" = "true" ]; then
          echo "Deploying to Cloud Run..."
          gcloud run deploy ${_SERVICE_NAME} \
            --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID} \
            --region=${_REGION} \
            --platform=managed \
            --memory=${_MEMORY} \
            --cpu=${_CPU} \
            --timeout=${_TIMEOUT} \
            --max-instances=${_MAX_INSTANCES} \
            --set-env-vars="SNAKEMAKE_CORES=${_CPU},SNAKEMAKE_MEMORY=${_MEMORY%Gi}G" \
            --execution-environment=gen2 \
            --allow-unauthenticated \
            --quiet
          
          echo "Deployment completed!"
          gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format="value(status.url)"
        else
          echo "Skipping Cloud Run deployment (DEPLOY_CLOUDRUN=false)"
        fi
    waitFor: ['test-container']

  # Step 5: Update GKE deployment (conditional)
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-gke'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_GKE}" = "true" ]; then
          echo "Deploying to GKE..."
          
          # Get cluster credentials
          gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone=${_ZONE}
          
          # Update deployment
          kubectl set image deployment/${_SERVICE_NAME} \
            pipeline=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID} \
            -n ${_NAMESPACE}
          
          # Wait for rollout
          kubectl rollout status deployment/${_SERVICE_NAME} -n ${_NAMESPACE} --timeout=600s
          
          echo "GKE deployment completed!"
        else
          echo "Skipping GKE deployment (DEPLOY_GKE=false)"
        fi
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    waitFor: ['test-container']

  # Step 6: Run integration tests (optional)
  - name: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID}'
    id: 'integration-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_RUN_TESTS}" = "true" ]; then
          echo "Running integration tests..."
          # Test dry run
          snakemake --dry-run --quiet || exit 1
          echo "✅ Dry run test passed"
          
          # Test help command
          snakemake --help > /dev/null || exit 1
          echo "✅ Help command test passed"
          
          echo "All tests passed!"
        else
          echo "Skipping integration tests (RUN_TESTS=false)"
        fi
    waitFor: ['push-image']

# Store built images
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

# Build options
options:
  machineType: '${_MACHINE_TYPE}'
  diskSizeGb: '${_DISK_SIZE}'
  substitutionOption: 'ALLOW_LOOSE'
  logging: GCS_ONLY

# Timeout for the entire build
timeout: '${_BUILD_TIMEOUT}'

# Substitution variables (can be overridden)
substitutions:
  # Image configuration
  _REGION: 'us-central1'
  _REPO_NAME: 'amr-pipeline'
  _IMAGE_NAME: 'amr-pipeline'
  
  # Deployment configuration
  _DEPLOY_CLOUDRUN: 'false'
  _DEPLOY_GKE: 'false'
  _RUN_TESTS: 'true'
  
  # Cloud Run settings
  _SERVICE_NAME: 'amr-pipeline'
  _MEMORY: '16Gi'
  _CPU: '4'
  _TIMEOUT: '3600'
  _MAX_INSTANCES: '5'
  
  # GKE settings
  _CLUSTER_NAME: 'amr-pipeline-cluster'
  _ZONE: 'us-central1-a'
  _NAMESPACE: 'amr-pipeline'
  
  # Build machine settings
  _MACHINE_TYPE: 'E2_HIGHCPU_8'
  _DISK_SIZE: '100'
  _BUILD_TIMEOUT: '1800s'

# Cloud Build service account permissions needed:
# - Cloud Run Admin (for deployment)
# - Container Admin (for GKE deployment)
# - Artifact Registry Writer (for image push)
# - Storage Admin (for build logs)